version: '3'
services:
  web:
    build: .
    ports:
    - "3005:3005"
  api:
    build: api/.
    ports:
    - "9080:9080"
    links:
    - mysql:mysql
  mysql:
    image: mysql
    build: database/.
    restart: always
    ports:
      - "42333:3306"

