version: '3'
services:
  web:
    build: .
    links:
    - api:api
    volumes:
    - /Users/jeffmills/Sites/mine/toppy:/Users/jeffmills/Sites/mine/toppy
    ports:
    - "3006:3006"
  api:
    image: api
    build: api/.
    ports:
    - "9080:9080"
    links:
    - mysql:mysql
    volumes:
    - /Users/jeffmills/Sites/mine/toppy/api:/Users/jeffmills/Sites/mine/toppy/api
    - /Users/jeffmills/Sites/mine/toppy/api/node_modules/
  mysql:
    image: mysql
    build: database/.
    restart: always
    ports:
      - "42333:3306"

